[package]
name = "mc-fog-block-provider"
version = "5.1.1"
authors = ["MobileCoin"]
edition = "2021"
description = "Provide blocks from a local or remote ledger database"
license = "Apache-2.0"
rust-version = { workspace = true }

[dependencies]
mc-blockchain-types = { path = "../../blockchain/types" }
mc-ledger-db = { path = "../../ledger/db" }
mc-mobilecoind-api = { path = "../../mobilecoind/api" }
mc-transaction-core = { path = "../../transaction/core" }
mc-watcher = { path = "../../watcher" }

displaydoc = "0.2"
dyn-clone = "1.0.16"

[dev-dependencies]
